### ISSUE TITLE
Target AoA

### ISSUE THREAD

**Issue by Kerbinator-Fras** [linuxgurugamer/KramaxAutoPilot#15]
Target AoA is important for highly optimized stock crafts, indeed.
_Especially when your wings have incidence angles (pre-rotated in SPH to optimize L/D and eliminate body drag for the most, I'll abbreviate it as AoI), this can be very problematic since your craft will want to pitch itself to AoA+AoI=0(for ship, so wing AoA=0),_ so you will find when you try to **point this craft to dead center prograde which is the most common flight status for extremely optimized stock-aero crafts**, this craft's actual ship AoA will be a bit (about 0.5-1 deg) lower than the prograde vector, which can lower the L/D from 4.4 to 2+, which is really horrible. In this case smart A.S.S of MechJeb also points downwards than prograde vector like stock SAS.
For large crafts such as my Eve SSTO I can solve it by using stock SAS, toggle canard to deploy (to disable it from pitch control and force its pitch up torque) and then manually adjust canard deploy angle to make the pitch to 0.0deg ship AoA (as I see in AeroGUI to monitor my ship AoA). This ship has another pair of elevon 4 to be controlled by SAS so it won't be problematic
but with my 🤔-64 SSTO (20 tonnes tiny single-RAPIER-single-Nerv high performance SSTO for interplanetary uses) which is too small to own more than 1 pair of elevon 4 in pitch axis this is very problematic
hope you to add this feature.

**Comment by Kerbinator-Fras** [comment]
Need to be executed:
Target AoA value (ship pitch - surface velocity pitch)

**Comment by linuxgurugamer** [comment]
This mod is in maintenance mode, I'm not adding to it.  Try using Atmosphere Autopilot, it has a lot of options
Sorry
