### ISSUE TITLE
Heading Hold not working

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/KramaxAutoPilot#2]
Heading hold seems to be completely jacked.  Normally when you activate it, it automatically sets the target heading to whatever heading you're currently at.  Now, it just defaults at 0.00, and when you try to adjust it to anything, it banks the aircraft and doesn't seem to ever settle out at any particular heading.  NAV mode seems to work fine, though.  I've done a few KSC ILS 27 approach/landings with zero issues. 
I second the stuff about the heading hold function...this has happened to me once as well.  No, I wasn't using 2 autopilots at the same time this go round

**Comment by TedThompson** [comment]
I can verify this is happening.  I came here to report, but found this thread open.

It seems to affect all craft.

**Comment by linuxgurugamer** [comment]
Should be fixed in 3.4.0, only on KSP 1.3.1
